Fix python3 compability issue
  File ".../python/site-packages/edit_server/server.py", line 48, in do_GET
    self.wfile.write('edit-server is running.\n')
  ...
TypeError: a bytes-like object is required, not 'str'